### PR TITLE
Upgrade/limit menu ingrent/task 11348

### PR DESCRIPTION
**Pull request by josemorin**

### CODE REVIEW

**Comment by coderdave** [comment]
please demo this to PO first

**Comment by ArmandoD97** [comment]
Rails test and functional testing worked well, didn't find any errors by my side. 

Great job!

**Review by faustino-garcia — APPROVED** [review]
Good Job guys

I just review your changes and everything looks good. I run the test suite and it came with no errors.

**Review by ArmandoD97 — APPROVED** [review]
Rails test and functional testing worked well, didn't find any errors by my side.

Great job!

**Review by AlexRS90 — CHANGES_REQUESTED** [review]
## Hello @josemorin 
### Good job so far!
Your implementation is good and it should works!
But I'm facing and issue when I tried to sign in! Here is the SS 👇 
image

### And the same error is been reflected in the tests: 
test errors

As a suggestion, I think is a good idea to write a description for the PR, we can have a better idea about your work in the current branch!

**Review by coderdave — CHANGES_REQUESTED** [review]
Please add tests

**Pull request merged**
